language: python
python:
    - "3.6"

# command to install dependeencies
install : "sudo pip install -r requirements.txt"

before_script:
    - flake8 --count --exclue ./tests,./doc --ignore E402,F401,E501

# command to run tests
#script: 
#sudo: required

